trigger: none

pool:
  vmImage: ubuntu-latest


stages:
- stage: stage1 
  displayName: My first stage
  jobs:
  - job: job1
    displayName: My first job
    steps:
      - script: echo "Hello world"
        displayName:  my first pipeline